### ISSUE TITLE
Dwm larbs install

### ISSUE THREAD

**Issue by taoz3n** [LukeSmithxyz/LARBS#231] opened 2020-05-19 18:01 UTC
I recently had a situation where I chose the i3 option with larbs and it instead installed dwm, that option had since been worked out and I have it installed on my w520 running just fine.  Yesterday I went to install the dwm option on my p72 and no go.  I tried 3 times and it will install dwm and it will begin to start up but immediately kick me out and go back to login. I checked the xinitrc and the i3 options were commented out and the dwm option was uncommented.  Any assistance anyone can give me to correct this would be much appreciated!!!

**Comment by LukeSmithxyz** [comment] 2020-05-19 18:36
Install `libxft-bgra`. Duplicate of https://github.com/LukeSmithxyz/voidrice/issues/610.

**Closed by LukeSmithxyz** 2020-05-19 18:36 UTC
