### ISSUE TITLE
i3 option sets dwm as default wm

### ISSUE THREAD

**Issue by Ramojus** [LukeSmithxyz/LARBS#221] opened 2020-05-03 13:08 UTC
When I started the script, I chose i3, but I got dwm as default wm. To make sure, I ran the script again, choosing i3 and same thing happenend.

**Comment by juxuanu** [comment] 2020-05-05 20:33
The same happened to me, but viceversa. I chose dwm, it installed i3

**Comment by LukeSmithxyz** [comment] 2020-05-05 21:38
Just to be clear, the script will always install both wms. The issue is which is started by `startx`.

Show me the contents of `~/.xinitrc`. dwm should be default, but the i3 lines should be uncommented by the script if you select them.

**Comment by taoz3n** [comment] 2020-05-13 11:25
Good morning Luke it’s Devon, I emailed you last night. I’m still fairly new to GitHub so I just found this section. As per my email I’ve had this issue several times for a while now and I even uncommented the i3 lines and commented out the for dwm. Prior to commenting out the dwm line after choosing the i3 option it starts to open the with the dwm bar up top then immediately kicks you out of the system. After commenting out the lines for dwm and uncommenting the lines for i3 it’s the same thing as I mentioned a second ago. I tried it again this morning with 3 new fresh base arch installs and the same result. I don’t know if this matters but the machine I’m installing on is a ThinkPad w520.

**Comment by LukeSmithxyz** [comment] 2020-05-13 11:54
Fixed in fd9c97310a46fdd56cd5407a9a2df7993bc529e4. The issue was that I had changed the relevant lines in the `~/.xinitrc` to use `ssh-agent` rather than `exec`, but neglected to change the sed command that edited them in the LARBS script.

If you already installed want to change the "default" WM, edit `~/.xinitrc` manuall and there are instructions.

**Closed by LukeSmithxyz** 2020-05-13 11:54 UTC
