### ISSUE TITLE
Unable to follow links in zathura

### ISSUE THREAD

**Issue by lyh970817** [LukeSmithxyz/LARBS#150] opened 2019-12-21 13:08 UTC
It seems that when typing in f I do get the right selection prompt and on typing in a number plus enter there is no error. But no browser is opened.

**Comment by LukeSmithxyz** [comment] 2020-02-09 12:41
This is an issue with Brave at the moment I believe. I'll try and figure it out.

**Comment by lukerb52** [comment] 2020-04-01 18:10
Issue replicated here.

**Comment by lukerb52** [comment] 2020-04-01 18:11
Issure replicated on my machine

Although on my machine, I have the $BROWSER var set to qutebrowser. Shouldn't that let it handle links?

**Comment by LukeSmithxyz** [comment] 2020-04-01 18:52
Well I should say the problem is with chromium-based browsers generally and qutebrowser is one.

**Comment by LukeSmithxyz** [comment] 2020-09-12 15:49
Fixed in https://github.com/LukeSmithxyz/voidrice/commit/426979aa7250e1d09b1f6044020d3f2b538425a9

**Closed by LukeSmithxyz** 2020-09-12 15:49 UTC
Labels: external bug
