### ISSUE TITLE
Icons are not shown properly at status bar.

### ISSUE THREAD

**Issue by Weirdei** [LukeSmithxyz/LARBS#52] opened 2018-09-16 13:44 UTC
On a fresh installation icons are not shown properly at status bar.
Fixed it by installing ttf-emojione.
Sorry, i didnt do screenshot before fixing. But its reproducible 100% time.

**Comment by LukeSmithxyz** [comment] 2018-09-18 21:49
Duplicate of LukeSmithxyz/voidrice#92

**Closed by LukeSmithxyz** 2018-09-18 21:49 UTC
